[package]
name = "p2sh"
version = "0.1.0"
authors = ["Robert Klotzner <robert.klotzner@gmx.at>"]
edition = "2018"

[dependencies]
termios = "0.3.2"
libp2p = {version= "0.17.0", path= "../rust-libp2p"}
async-std = "1.5.0"
futures = "0.3.4"
env_logger = "0.7.1"
